### PR TITLE
Get the scrape code running again

### PR DESCRIPTION
**Pull request by bmcorser**
We changed the target interaction entity from `optevia_...` to `detica_...` which has necessitated another scrape run. This PR holds code changes related to that.

### CODE REVIEW

**Comment by ztolley** [comment]
Are you able to get Travis working again?

**Comment by bmcorser** [comment]
I'll look into it today.

**Comment by bmcorser** [comment]
It looks like the Django app is missing database config, trivial to add it; will bug @sdonk tomorrow 😅

**Comment by ztolley** [comment]
In the travis job? Easy fix if it is as it's using djdatabase for it's config

**Pull request merged**
