### PR TITLE
Sprint 13

### PR DESCRIPTION
**Pull request by bmcorser**
Oh no, I didn't manage to push. Better watch out for buses on the way home!

🏃 🚌

### CODE REVIEW

**Comment by bmcorser** [comment]
PS @sdonk I changed the migrations again 💃

**Comment by sdonk** [comment]
sprint 13 again?

**Comment by bmcorser** [comment]
Sorry, should have been `sprint-13-loose-ends` or something

**Comment by sdonk** [comment]
LGTM

**Comment by sdonk** [comment]
LGTM

**Comment by bmcorser** [comment]
LGTM

**Pull request merged**
